### ISSUE TITLE
German symbols are not displaying correctly

### ISSUE THREAD

**Issue by Donny5300** [Polyconseil/vue-gettext#102]
Hi,

Im using gettext for a project in 3 different languages. NL, EN and DE. For the DE store i need to translate words with the sign ß. The system doesnt display the sign but shows a question mark. How can i fix this? 

Line of JSON: `"reset_popup_information": "Sie wechseln gerade zwischen Innen- und Außenbeleuchtung. Alle getroffenen Entscheidungen gehen verloren. Möchten Sie die Beleuchtungsart noch ändern? ",`

Basic code: 
```
Vue.use(GetTextPlugin, {
    translations: {
        nl: translationsNL,
        en: translationsEN,
        de: translationsDE,
    },
    defaultLanguage: window.SHOP.lang
});
```

Domain: https://www.cottonballlights.com/de/selber-zusammenstellen-8812387/

![Schermafbeelding 2019-11-08 om 17 08 11](https://user-images.githubusercontent.com/4244962/68491129-86c34100-024a-11ea-80f0-ff69163f685e.png)

**Comment by kemar** [comment]
Hi, this looks like a CSS font-family issue.

I just tested the `Eszett` locally and it works:

![s](https://user-images.githubusercontent.com/281139/68499738-394ed000-025a-11ea-9e6c-4cf0b9530bb8.png)

**Comment by Donny5300** [comment]
Thank you for your response.

Changing the font-family in the code doesn't change anything. Can you show me your code or take a look at the domain i gave?

**Comment by kemar** [comment]
> Can you show me your code

The code is located in the repo: https://github.com/Polyconseil/vue-gettext/tree/master/dev ([doc](https://github.com/Polyconseil/vue-gettext/blob/master/README_DEV.md#dev-setup)). You can run it and change translations.

I looked at your domain.

It looks like the JavaScript file located here https://cdn.webshopapp.com/shops/271302/themes/156248/assets/vue-configurator.js is not UTF-8 encoded:

![screen](https://user-images.githubusercontent.com/281139/68547337-8eb4e980-03e0-11ea-8537-7225c7aff73a.png)

This is your problem.

**Comment by Donny5300** [comment]
Do you have a idea how to fix this issue?

**Comment by kemar** [comment]
Not really, sorry. I don't know how your JS build toolchain is constructed.

Maybe check that the shell in which you're running `make makemessages` and `make translations` is UTF-8 ready, e.g.:

```shell
$ echo $LANG
fr_FR.UTF-8
```

I'm closing this issue since it's not related to the plugin itself.
