### ISSUE TITLE
issue running gettext-extract

### ISSUE THREAD

**Issue by lfglopes** [Polyconseil/vue-gettext#103]
After a dependencies update, when i run 

`gettext-extract --attribute v-translate --quiet --output /tmp/template.pot ./src/App.vue ./src/.....`

The following pops out:

`No configuration found`

I realised the dependent package [gettext-extract](https://github.com/sinedied/gettext-extract) requires now a `.gettext.json` configuration file

**Comment by kemar** [comment]
There may be some misunderstanding. The [`gettext-extract`](https://github.com/Polyconseil/vue-gettext#how-does-vue-gettext-work-at-a-high-level) used in vue-gettext comes from [easygettext](https://github.com/Polyconseil/easygettext).

There is no dependency on the package you mention.

**Comment by lfglopes** [comment]
you're right, nevermind. i guess at some point i didn't have `gettext-extract` available and pulled in the wrong dependency. thanks and apologies
