### ISSUE TITLE
Lazy loading translations

### ISSUE THREAD

**Issue by hworld** [Polyconseil/vue-gettext#12]
For big apps loading all the translations in before bootstrapping the app can be quite a bit of waiting.

I think I came up with a solution that may work. My main goals were:
- You should be able to insert translations into the "library" of translations at any time.
- The page should react without having to load the page all over again.
- The reactivity should be light and only update components that really did change. 
- Let the developer decide how to fetch the translations.

Here's what I came up with: https://github.com/gamejolt/vue-gettext/commit/327112b729519c2b205fd0804cde8a8a66fc652a
You can see that it's pretty minimal changes to the code. I also just modified the dist file so you could get an idea of what I did. I'm not sure if you like this solution.

You basically use it like this in a Vue component:
```js
async created()
{
	const translations = await $import( '!!../../../translations/en_US/main.json' );
	this.$language.addTranslations( translations );
}
```

All I did was attach a new method to add translations on the main languageVm component. I added a new reactive data property to it which is the object of ALL translations. This can be a lot of observable wrapping, though in my testing it was really really fast.

I modified the `getTranslation()` to use the language vm which properly set up the dependencies for each bound part of my app. I made a little script that would remove translations, then add them back, and continue swapping. Only the translations that changed were updated in the DOM. The rest weren't touched when looking at the JS profile (though you can do your own tests if you like).

It also works for computed properties that use the `this.$gettext` type of functions since Vue is able to find the dependency on the language vm property.

**Comment by kemar** [comment]
> For big apps loading all the translations in before bootstrapping the app can be quite a bit of waiting.

Just for reference, how big is your JSON `translations` file? How long does it take to fetch it over the network?

> You basically use it like this in a Vue component

Ok, I can see how your implementation works. You have to fetch a splitted part of translations in a component's created hook. But now you have to display a loading state while the data is being fetched over the network. Still, it may be quicker than loading one big `translations` file.

> `$import('!!../../../translations/en_US/main.json')`

I never saw this syntax before: could you please explain me why there is a `$` prefix before `import` and why the import path starts with a double exclamation mark? Is this a Webpack specific syntax?

> This can be a lot of observable wrapping, though in my testing it was really really fast.

Your proposal looks like a quite possible way to implement lazy loading.

However, I have no time to work on it now and there has been little demand so far. So I will not work on this until it become a major issue for a lot of users.

But please feel free to open a proper pull request and in this case, be sure to:

- provide an easy and clear solution to generate multiple `translations` files during the extraction step
- add comments
- add tests (including tests that track the number of observables before and after a lazy loading)
- include one or more examples in the `dev` part of the project
- add documentation

**Comment by hworld** [comment]
Ah, too bad. I don't have much time either. Hopefully someone can come along and see this and work on it more. Here is a translation po file for the site. Note that only about half of the site is annotated so this would continue to grow: https://github.com/gamejolt/translations/blob/master/en_US/main.po

The main JSON file for the app is 10kb gzipped. I then split out another one for the "account" part of the site which ends up being 10kb. I then also have ones for different sections like auth, checkout, etc.

I didn't really want to solve the "how" of generating multiple translations files because I think it's very app-specific. For example, I just look at the paths of all the files where the translation is contained and then take the first bit "app" "checkout" "auth" and split them into their own files. They could even just loop your makefile thing over certain folders in their source tree and just do it that way.

Sorry, the `$import` thing is a bit silly. You can read it as this in webpack:

```js
require.ensure( '../../../translations/en_US/main.json' ).then( ... )
```

I didn't want to solve the loading of translations because that should be done by the app. Maybe they would use webpack, maybe browserify, maybe just using an ajax call. Either way, they would get the translation eventually and add it to the library of translations. I would assume that they would still bootstrap their app with the main translations needed for their app shell when they initialize the plugin, but can load in extra translations as the user navigates routes and what not.

I guess calling this "lazy loading" is maybe not the best thing, since it doesn't deal with loading. It's more just the ability to add translations in during run time.

**Comment by laurentpayot** [comment]
@kemar  web apps (including PWA) can not be build for a specific language like native apps. Loading all the languages (in one of my apps 4 of them) as webpack assets bloats the built for no reason. Too bad. I have to stick to vue-i18n.
