### ISSUE TITLE
vue3 support

### ISSUE THREAD

**Issue by nanu-c** [Polyconseil/vue-gettext#126]
Currently the plugin fails with vue3. Are there plans to add support for vue3?

```
Uncaught TypeError: Vue is not a constructor
    GetTextPlugin vue-gettext.js:878
    use runtime-core.esm-bundler.js:2976
    <anonymous> main.js:42
    js app.js:1628
 ```

**Comment by nanu-c** [comment]
Looking into the code, i see it needs lots of effort.

**Comment by kemar** [comment]
Hi @nanu-c Nope, there is no plan to support for Vue 3 (see https://github.com/Polyconseil/vue-gettext/pull/118)

**Comment by nanu-c** [comment]
Hey kemar the `vue-native-websocket-vue3` is a drop in replacement for this module and it works without changing anything, so there is really no need to to it ;)
