### ISSUE TITLE
Improvement: Better ordering of translation references in .po files

### ISSUE THREAD

**Issue by trainiac** [Polyconseil/vue-gettext#13]
When generating .po files the translation references order makes a translation flow difficult

This is an example of translation reference output order:
```
#: client/components/A.vue:7
#: client/components/A.vue:17
#: client/components/B.vue:20
#: client/components/B.vue:24
#: client/components/C.vue:11
#: client/components/D.vue:29
#: client/components/B.vue:3
#: client/components/A.vue:12
#: client/components/C.vue:12
#: client/components/D.vue:36
#: client/components/A.vue:39
#: client/components/D.vue:22
#: client/components/A.vue:44
#: client/components/D.vue:76
#: client/components/D.vue:77
#: client/components/C.vue:63
#: client/components/C.vue:64
#: client/components/C.vue:65
```

I would expect, translations would be grouped by file (or path) and within the file (or path) they would be in order of line number.

Desired output

```
#: client/components/A.vue:7
#: client/components/A.vue:12
#: client/components/A.vue:17
#: client/components/A.vue:39
#: client/components/A.vue:44
#: client/components/B.vue:3
#: client/components/B.vue:20
#: client/components/B.vue:24
#: client/components/C.vue:11
#: client/components/C.vue:12
#: client/components/C.vue:63
#: client/components/C.vue:64
#: client/components/C.vue:65
#: client/components/D.vue:29
#: client/components/D.vue:22
#: client/components/D.vue:36
#: client/components/D.vue:76
#: client/components/D.vue:77
```

vue-gettext 2.0.8
Mac Os Sierra 10.12.3
gettext 0.19.8.1
easygettext 1.2.2

**Comment by vperron** [comment]
That should probably be up to the choice of the user; in my projects I usually don't want to reorder the whole PO file whenever I move source file around as it makes i difficult to follow what actually changed.

But my guess is it could be a simple option in th Makefile ?

**Comment by trainiac** [comment]
That's a good point.  Well if there is any order now what is it? There should be some predictable order

**Comment by vperron** [comment]
I guess it's alphabetic, following the msgid (instead of source file(s)) as you suggest; the order is then kept as stable as possible upon new insertions, still alphabetic.

Actually what you suggest is complicated because if the string "Hello World" is present in two different source files gettext will still aggregate those in order to translate it only once (unless the msgctxt is difefrent, of course)

Which means the list of source files before a given msgid may be multiple and you'll be unable to sort it anyway at this level.

**Comment by kemar** [comment]
@trainiac you can customize your Makefile target by adding `--sort-by-file` and `--sort-output` arguments. Just have a look at the [`msgattrib` documentation](https://www.gnu.org/software/gettext/manual/html_node/msgattrib-Invocation.html#msgattrib-Invocation).

Also note that `--sort-output` is not recommended:

> Note that using this option makes it much harder for the translator to understand each message’s context.

As mentioned by @vperron the order depends on personal taste. This choice is left to each developer.

**Comment by trainiac** [comment]
@kemar Awesome.  I figured some of these issues I was having were options with underlying libraries.  You've been a great help.  --sort-by-file is sufficient for my need.

@vperron FYI, having tested this when sorting by files and there are two different files that use the same translation, the file that comes second is grouped together with the first file the translation instance was found. So it's not a truly in sort-by-file order, but it's kind of the best of both worlds.
