### ISSUE TITLE
Events don't get bound to translation component

### ISSUE THREAD

**Issue by trainiac** [Polyconseil/vue-gettext#14]
Passing bound properties and unbound properties to the `translate` component seem to make there way to the underlying element that gets rendered. However event handlers do not. In the example below the "@click" is not attached to the button at runtime. 

Desired API
```html
      <translate
        tag='button'
        type='button'
        @click='$emit("forgotPasswordClick")'
        :class='[$style.forgotPassword, $css.helpers.linkBtn]'
      >
        Forgot password?
      </translate>
```

Perhaps making translate directives instead of components would solve problems like these? This is probably huge scope creep but thought I'd throw it here for completion sake.

Desired API 2
```html
      <button
        v-gettext-translate
        type='button'
        @click='$emit("forgotPasswordClick")'
        :class='[$style.forgotPassword, $css.helpers.linkBtn]'
      >
        Forgot password?
      </button>
```

Works for now API
```html
      <button
        type='button'
        @click='$emit("forgotPasswordClick")'
        :class='[$style.forgotPassword, $css.helpers.linkBtn]'
      >
        <translate>Forgot password?</translate>
      </button>
```

vue-gettext 2.0.8

**Comment by kemar** [comment]
Yes, the *Works for now API* that you describe is currently the way to go.

I tried to build a directive during the development of the plugin but could'nt end up with a working solution.

But if you know how to implement such a directive, please feel free to submit a pull request!

**Comment by trainiac** [comment]
Thanks @kemar. I'm still learning vue myself but I may try to build this  as a directive if I have time in the future.

However for now, I figured out a solution to this problem. In general in vue, when binding a native event to a custom component such as the `translate` component you have to add the `.native` modifier. So for people trying to bind click events or other native events to a tag do this

Desired API
```html
      <translate
        tag='button'
        type='button'
        @click.native='$emit("forgotPasswordClick")'  // Note the .native modifier
        :class='[$style.forgotPassword, $css.helpers.linkBtn]'
      >
        Forgot password?
      </translate>
```
