### ISSUE TITLE
Evaluation of nested objects in expressions does not work

### ISSUE THREAD

**Issue by lattam** [Polyconseil/vue-gettext#24]
Hi, I have found one more issue connected with https://github.com/Polyconseil/vue-gettext/issues/23 when evaluating nested objects in nested components: 

```
<template>
  <!-- ... -->
    <md-layout>
        <translate>User: %{ user.firstname }</translate>
    </md-layout>
  <!-- ... -->
</template>
```

The result is: 

`User: user.firstname`

(plus some warnings in console _Cannot evaluate expression: "user.firstname"_.)

Problem occurs when the function [evalInContext](https://github.com/Polyconseil/vue-gettext/blob/master/dist/vue-gettext.js#L444) tries to evaluate:

`eval('this.' + nested_expression)  === undefined`

which throws an error instead of continuing into the parent component. The solution might be to check the expression with nested object more carefully (or somehow prevents the _eval_ in condition to throw an error)

```
// check if "this" object contains "expression" 
var result = expression.split('.').reduce(function (value, index) {
   return (value || { })[index]
}, this)

if (result === undefined && this.$parent) {
  return evalInContext.call(this.$parent, expression)
}
```

The code above is inspired by [this topic](http://stackoverflow.com/questions/2631001/javascript-test-for-existence-of-nested-object-key)

**Comment by kemar** [comment]
Previous commit broke recursion. I'll fix it ASAP.

See: https://github.com/Polyconseil/vue-gettext/commit/29c5673aff7b7712d7ced61c003e6d3b55e68873#commitcomment-22242469
