### ISSUE TITLE
access to the dictionary outside of a Vue instance

### ISSUE THREAD

**Issue by svewag** [Polyconseil/vue-gettext#25]
Is there a possibility to access the dictionary outside of a Vue instance?
Something like 

> Vue.$gettext('key')

**Comment by kemar** [comment]
Yes, `Vue.$translations` is exposed, you can do `Vue.$translations['en_GB']['key']`.

You can also [read the doc](https://github.com/Polyconseil/vue-gettext#configuration) before opening an issue :p
