### ISSUE TITLE
using array of translations for plural

### ISSUE THREAD

**Issue by fyyyyy** [Polyconseil/vue-gettext#26]
Hello
My Json sometimes has an array, the first is singular, the second is the plural translation.
How do i tell it to use plural ? Currently vue-gettext uses only the first array property.

```js
    "Delete Workshop":["Werkstatt löschen", "Werkstätten löschen"],
```

**Comment by kemar** [comment]
Mark your string as translatable using `translate-n` and `translate-plural` [as described in the documentation](https://github.com/Polyconseil/vue-gettext#plural).

**Comment by fyyyyy** [comment]
Thanks but i believe this does not work, because the key is always singular.

```html
<translate>Delete Workshop</translate>
<translate>Delete Workshops</translate> // doesnt exist
```

I would have to change the json file to add a plural key.

**Comment by kemar** [comment]
In the `translate-n="count"` expression, the `count` value will trigger either the singular or the plural string to be displayed, depending on its value and the current language. If your `count` value never change, you will never see the plural.

I can't help you more without a proper example. If you want more help please provide a full JSFiddle reproducing your issue.

**Comment by fyyyyy** [comment]
I have tried different count values.

```html
<translate translate-n="count" translate-plural="Delete Workshop">Delete Workshop</translate></span>
```

Since i provide the same key for plural and singular, the displayed translation in German is always "Werkstatt löschen", and never goes to "Werkstätten löschen"

**Comment by rbarrois** [comment]
@fyyyyy Indeed, you need to provide different keys for singular and plural, e.g ``Delete Workshops``.

**Comment by fyyyyy** [comment]
I am working with a 3rd party JSON which was generated from gettextCatalog.
Unfortunately i cannot change the JSON for this project. 
I was wondering however why its using the first element in the array rather than displaying the contents of the entire array.
