### ISSUE TITLE
translate tag not properly updating

### ISSUE THREAD

**Issue by fyyyyy** [Polyconseil/vue-gettext#27]
I have an issue where the translate tag isnt updated when the transcluded content changes in a child component.

```

// doesn't work
<translate>
  <slot></slot>
</translate>

// works fine
<slot v-translate></slot>

**Comment by kemar** [comment]
I think that could be a `slot` misuse, see the [Vue.js documentation](https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots).

Instead you should try something like this:

```html
<slot>
  <translate>This will only be displayed if there is no content to be distributed.</translate>
</slot>
```

**Comment by fyyyyy** [comment]
Hmm from what i read, i can place the slot element anywhere in my child component ?

**Comment by fyyyyy** [comment]
`<translate>Delete {{selected.count}} Users</translate>`
This also will not update, i guess its a general issue that the content isnt watched, or is this intended ?

**Comment by kemar** [comment]
This can't work because instead of the "Mustache" syntax (double curly braces), you have to use `%{` and `}` [as noted in the documentation](https://github.com/Polyconseil/vue-gettext#interpolation-support).

So instead of:

```html
<translate>Delete {{selected.count}} Users</translate>
```

Use:

```html
<translate>Delete %{ selected.count } Users</translate>
```

**Comment by fyyyyy** [comment]
I tried this, it didnt update either

**Comment by fyyyyy** [comment]
E.g. i have a feeling this should work in any child component. The variable is defined, and it renders the text but it does not translate it. Also when switching languages, it will always display the plain text.
        `<translate>%{ $slots.default[0].text }</translate>`

this however works
        `<translate>{{ $slots.default[0].text }}</translate>`


Versions
    "vue": "^2.3.3",
    "vue-gettext": "^2.0.15",
    "vue-router": "^2.3.1",
    "vuex": "^2.3.1"

**Comment by fyyyyy** [comment]
Ok i think i found the source of the first issue. If the translation is not found, the text **never** updates regardless of variable or tag content changes. Maybe this should throw a warning or something :)

**Comment by fyyyyy** [comment]
oh crap, i had silent: true 🙈  
Thanks for the help, I will send you some free miles for car2go 🚗
