### ISSUE TITLE
translation() crashes when a msgid exists with and without a context

### ISSUE THREAD

**Issue by narrowtux** [Polyconseil/vue-gettext#32]
For some common words, like "Name", you'll have your msgid repeated a lot over the codebase. Sometimes it will be with a context, and sometimes without a context.

If a message exists with both a context and without a context, `easygettext compile` will create this entry in the translation JSON file:

```json
{
    "Name": {
      "": "Name",
      "some-context": "Name"
    }
}
```

Now when using `<translate>Name</translate>`, vue-gettext will crash with this error:

```
app.js:22769 TypeError: Cannot read property 'replace' of undefined
    at Function.interpolate (app.js:95796)
    at VueComponent.translation (app.js:95735)
    at Watcher.get (app.js:25020)
    at Watcher.evaluate (app.js:25120)
    at Proxy.computedGetter (app.js:25372)
    at Proxy.render (app.js:95751)
    at VueComponent.Vue._render (app.js:26141)
    at VueComponent.updateComponent (app.js:24683)
    at Watcher.get (app.js:25020)
    at new Watcher (app.js:25003)
```

(line numbers are off because of a missing source map in our app)

What I'm guessing is that it can't find the key `null` for context in the object, so its value is `undefined` and then the library tries to interpolate the value.

**Comment by kemar** [comment]
@narrowtux thanx for this bug report, it was easy to reproduce. I published a new release containing a fix for this problem : [v2.0.18](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.18).

@vperron is the empty string as an object key a bug in`easygettext compile` or is it the intended behavior?

**Comment by vperron** [comment]
As far as I remember it was an intended behaviour since there was no particular string that would fit the job perfectly. We could choose something like "__NOCONTEXT__" to be more explicit but with the issue of adding magic. 
In the current behaviour, the void key means a void context.

**Comment by kemar** [comment]
@vperron allright, understood. Thanx :)

**Comment by narrowtux** [comment]
Thanks for the fast fix, very nice! :+1:

2017-07-11 18:44 GMT+02:00 Marc Hertzog <notifications@github.com>:

**Comment by barakat-turki** [comment]
Hi @kemar,
I'm trying to use.
```js
<template>
  <div>
    <select name="language" v-model="$language.current">
      <option v-for="(language, key) in $language.available" :value="key">{{ language }}</option>
    </select>
  </div>
</template>
```
and also when try to passing locale key 
```js
vm.$language.current = 'ar_001'
```
I receiving  
`Cannot read property 'replace' of undefined`
**Note:** `vue-gettext` version is `2.0.25`
