### ISSUE TITLE
Unexpected character '`' error during build.

### ISSUE THREAD

**Issue by eldarc** [Polyconseil/vue-gettext#34]
When I execute `npm run build` or `yarn build`, I get the following error (`npm run dev` works):

> ERROR in static/js/vendor.ba9ed4263537ece56ce8.js from UglifyJs
> Unexpected character '`' [./~/vue-gettext/src/component.js:33,0][static/js/vendor.ba9ed4263537ece56ce8.js:26972,22]

If I add `resolve('node_modules/vue-gettext')` to `webpack.base.conf.js`, like this:
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-gettext')
        ]
      }
```
the build will be successful. But when I run the app in the browser I get the following error: `Uncaught TypeError: Cannot read property 'installed' of undefined`

The same error will occur when `npm run dev` or `yarn dev` is run.

**Comment by kemar** [comment]
Sorry, I cannot really help you on this one. Looks like a misconfiguration in your build.

It could come from UglifyJs. Also try to use the files available in `vue-gettext/dist` instead of those in `vue-gettext/src`.
