### ISSUE TITLE
Not trimming v-translate content

### ISSUE THREAD

**Issue by hworld** [Polyconseil/vue-gettext#35]
Hey there, I noticed in the code that you have a comment specifically saying you don't want to trim the content of the v-translate directive. I'm curious what the reason is for that. I have a lot of code that looks a bit like this: 

```
<p class="help-block" v-translate>
	This is some <b>help text.</b>
</p>
```

With the <translate> component it trims. When using v-translate it won't.

**Comment by kemar** [comment]
Because it's quite tricky to get raw HTML of a Vue component, but not in a Vue directive.

It is written in black in white in both code comments and [in the documentation](https://github.com/Polyconseil/vue-gettext#html-support).

**Comment by hworld** [comment]
I think you misunderstood my question. I understand the need for the v-translate directive over the translate component. I was curious why you weren't trimming the msgid in the v-translate directive, but you do trim it in the translate component.

**Comment by hworld** [comment]
Ah, just posting here that https://github.com/Polyconseil/vue-gettext/pull/38 solved the issue I was seeing.
