### ISSUE TITLE
Access gettext from winthin a custom filter

### ISSUE THREAD

**Issue by bilougit** [Polyconseil/vue-gettext#37]
Hi, I'm trying to translate my text through a custom filter which I've created but I'm not able to access the object `vm`

```javascript

import Vue from 'vue';
import GetTextPlugin from 'vue-gettext';
import translations from './translations.json';


Vue.use(GetTextPlugin, {
    translations: translations,
    defaultLanguage: 'fr',
});

Vue.filter('trans', function (value) {
    return vm.$gettext(value);
});

new Vue({
   el: '#app',
....
```

Doing this raises this error `Uncaught ReferenceError: vm is not defined`, How do I inject the translator into my filter?

**Comment by kemar** [comment]
Nope you can't access the `vm` from inside a custom filter, this is a Vue.js design choice, [read the documentation](https://vuejs.org/v2/guide/syntax.html#Filters):

> filters are primarily designed for text transformation purposes

Anyway if you really want to translate inside a filter (I wouldn't recommend it), you can use [the exposed instance methods](https://github.com/Polyconseil/vue-gettext/blob/3833a4f7f7f4bca81d327ed28e3ed9b8141996b5/src/index.js#L59-L64) like this:

```Vue.prototype.$gettext('Text to translate')```
