### ISSUE TITLE
Using v-translate in pug templates

### ISSUE THREAD

**Issue by pribilinskiy** [Polyconseil/vue-gettext#39]
Following `.vue` code:
```html
<template lang="pug">
	div
		p(v-translate) test
</template>
```

Leads to an error
```
vue.common.js:461 [Vue warn]: Property or method "v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

Is there any plans to support `pug` templating?

**Comment by kemar** [comment]
Nope, no plans to support `pug`.

There is a link [in the documentation](https://github.com/Polyconseil/vue-gettext#helper-library-for-using-template-languages-in-vues-single-file-component) on this point (please read the doc before opening an issue): https://github.com/kennyki/vue-webpack-gettext

**Comment by M0dM** [comment]
vue-gettext is working with pug & single file components.
Just use html for translated elements like this:
```pug
<p v-translate>
  |  Translate me :D
  |  <br>
  |  <br>
  |  <b>And me!</b>
</p>
```
