### ISSUE TITLE
Consider support for interpolation with HTML content

### ISSUE THREAD

**Issue by kemar** [Polyconseil/vue-gettext#4]
As Radu suggests:

```javascript
Vue.component('translate', Vue.options.components.translate.extend({
    props: {
        escapeHtml: {
            type   : Boolean,
            default: true
        }
    },
    render: function (createElement) {
        if (this.escapeHtml) {
            return createElement('span', [this.translation]);
        } else {
            return createElement(
                'span',
                {
                    domProps: {"innerHTML": this.translation}
                },
                [])
        }
    }
}));
```

In templates use a prop:

```javascript
<template>
    <div>
        <translate :escape-html="false">some text, %{br} some other text.</translate>
    </div>
</template>

<script type="text/ecmascript-6">
    export default {
        data() {
            return {
                br: '<br>'
            }
        }
    }
</script>
```

**Comment by hworld** [comment]
Just pasting this here in case it proves useful. This is how I handled it with my codebase:
https://github.com/gamejolt/vue-gettext/commit/ca1426192a91d47b8a8367423436df896aadfe1e

I use vnodes for all templates so it became a bit tricky to gather the HTML. Basically I just crawl over the vnodes and build out an HTML string. I skip any attributes and stuff for now, so this only allows really simple templates like: `<translate>You are <strong>cool!</strong></translate>`.

**Comment by kennyki** [comment]
Not sure if it will fulfill your requirements, but I have created a custom directive (instead of using the component) to support HTML content. You can check it out at https://github.com/Polyconseil/vue-gettext/pull/22

**Comment by kemar** [comment]
This can now be done with a directive since [release 2.0.14](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.14)
