### ISSUE TITLE
Number.isNaN not supported in IE 11

### ISSUE THREAD

**Issue by trainiac** [Polyconseil/vue-gettext#41]
Are you planning to support IE11?  The only issue I currently see is Number.isNaN is not supported in IE11, support winodw.isNaN. This is currently used in plurals.getTranslationIndex  Let me know and I'll submit a PR. Thanks

**Comment by kemar** [comment]
@trainiac thanx for the report, this is fixed in [v2.0.22](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.22).
