### ISSUE TITLE
Usage of plural

### ISSUE THREAD

**Issue by escapedcat** [Polyconseil/vue-gettext#42]
Hey, I'm kinda confused how plurals are working.  
I read the docs and some other issues related to plural and created this fiddle: https://jsfiddle.net/escapedcat/75peeeqy/1/  
`ITEM` and `ITEMS` should be translated to `Car` and `Cars`, but only `ITEM` translates correctly.

Is this supposed to work or not? If not can you highlight the paragraph in the doc where this is stated? I would try to rework the docs to make this more clear. If this sin't supposed to work, how could somethign like this be achieved?

**Comment by kemar** [comment]
And how do you expect it to work if you don't use a correct JSON format for the plurals in your translation object?

Use this in your fiddle and enjoy it working:

```javascript
Vue.use(VueGettext, {translations: {
    "ITEM": [
      "Item",
      "Items"
    ],
}});
```

And maybe you can read [some examples](https://github.com/Polyconseil/vue-gettext/tree/master/test/specs/json) before making me loosing my time :p

**Comment by escapedcat** [comment]
Thanks a lot for the hint. This works fine now: https://jsfiddle.net/escapedcat/sydeqk2c/
I'm still trying to wrap my head around gettext. Sorry for wasting your time :P

**Comment by kemar** [comment]
You can [read this for an introduction to the **classic** Gettext](http://www.labri.fr/perso/fleury/posts/programming/a-quick-gettext-tutorial.html) workflow.

But please note that Vue-gettext deviates from the original Gettext. Notably with regard to the way translations are exposed in a JSON format. You can learn more by reading the doc and inspecting [some dependencies](https://github.com/Polyconseil/vue-gettext#what-does-vue-gettext-depend-on) (`gettext-compile`).
