### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by pribilinskiy** [Polyconseil/vue-gettext#47]
We are on CentOS 7 and it has [`gettext v0.18.2`](http://rpmfind.net/linux/rpm2html/search.php?query=gettext
) which doesn't support `JavaScript` as the language

This plugin was inspired by `angular-gettext` that we use for AngularJS apps.
There were no issues even on CentOS 6, which has even an older version of `gettext v0.17.18`

Are there any plans to write a parser, like in `angular-gettext`, that would not depend on the version of `gettext`?

**Comment by kemar** [comment]
Not yet. I do not have the time.

However, it would be the best solution since it would fix other issues too.

Unfortunately, I cannot guarantee that I will work on it.
