### ISSUE TITLE
Whitespace with label and v-translate

### ISSUE THREAD

**Issue by pribilinskiy** [Polyconseil/vue-gettext#50]
Usually it's ok for elements like `translate` `button`, `span` to have whitespace, e.g.:

```html
<translate>  OK  </translate>
```
is correctly transformed to
```html
<span data-v-1eedad60="">Ja</span>
```

Another example:

```html
<button
	v-translate
>
	Cancel
</button>
```
is transformed to:
```html
<button data-msgid="
		Cancel
	" data-current-language="da_DK">Annuller</button>
```

But with `label`s there's a problem
```html
<label> Description </translate>
```
translates to:
```html
<label data-v-8ec943bc="" data-msgid=" Description " data-current-language="da_DK"> Description </label>
```
and only after removing the spaces, e.g. `<label>Description</translate>` the msg is translated

**Comment by kemar** [comment]
Hi @pribilinskiy 

I need more info to help you. Do you use the component or the directive?

Can you provide at least a link to a [minimal reproduction](https://github.com/vuejs/vue-issue-helper/blob/428607cb6601bdee4c0eb46f3592cffd36fbc544/src/i18n/locales/en/repro-modal.md) of your problem?

It can be a JSFiddle / JSBin / CodePen or GitHub repo.
