### ISSUE TITLE
Object.assign not supported in IE

### ISSUE THREAD

**Issue by tokyoincode** [Polyconseil/vue-gettext#52]
Hello! 

Somewhat related to #41 

I wanted to ask if you still have plans to support Internet Explorer; found out that `Object.assign()` is not supported in IE. [Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

[This line in particular](https://github.com/Polyconseil/vue-gettext/blob/8a36abfc336d09b104bc68d1258c56dd7c9ca0fe/src/index.js#L32)

Would be happy to help and open a PR once I get the tests to pass locally.

Thank you!

**Comment by kemar** [comment]
Hi @tokyoincode 

Yes, a PR is welcome :)

I was sure that the [`es2015`](https://github.com/Polyconseil/vue-gettext/blob/b4e5dd5f5528764d83c8c40ef500de38f13930e6/.babelrc#L2) preset included a polyfill for `Object.assign`. Turns out [it doesn't](https://babeljs.io/docs/plugins/preset-es2015/).

**Comment by tokyoincode** [comment]
Thank you! I do have one question. Even after a fresh clone, the 22 of the 73 tests fail; I must have missed something in the Contributing readme file, but not exactly sure what.

**Comment by kemar** [comment]
Cannot help you on this one, since tests are successful for me:

```shell
npm run test

> vue-gettext@2.0.23 test /Users/kemar/EnCours/polyconseil/dev/vue-gettext
> npm run lint && karma start build/karma.conf.js --single-run
> vue-gettext@2.0.23 lint /Users/kemar/EnCours/polyconseil/dev/vue-gettext
> eslint src test dev build

10 10 2017 12:27:02.708:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
10 10 2017 12:27:02.711:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 10 2017 12:27:02.716:INFO [launcher]: Starting browser PhantomJS
10 10 2017 12:27:04.267:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#FZ8kjcCo7oNvbnaDAAAA with id 74197783

[...]

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 73 of 73 SUCCESS (0.183 secs / 0.088 secs)
```

**Comment by tokyoincode** [comment]
Understood, thank you!

**Comment by tabe1hands** [comment]
@kemar 
I have the same problem. Then, I've found the cause. After `npm install`, `vue@2.4.4` is installed. To run the unit tests, we should specify the `vue` version to `2.1.6`:

```patch
diff --git a/package.json b/package.json
index 3e8418b..bd788a1 100644
--- a/package.json
+++ b/package.json
@@ -61,7 +61,7 @@
     "sinon-chai": "^2.8.0",
     "style-loader": "^0.13.1",
     "uglify-js": "^2.7.4",
-    "vue": "^2.1.6",
+    "vue": "2.1.6",
     "vue-loader": "^10.0.0",
     "vue-template-compiler": "^2.1.6",
     "webpack": "^1.13.3",
```

**Comment by tabe1hands** [comment]
Should I create pull request about the problem of the unit tests?

**Comment by tokyoincode** [comment]
Yup, tests seem to pass if Vue `2.3.4` and lower is installed. Must have been a big change in the  `Kill la Kill` release.

**Comment by kemar** [comment]
@tabe1hands ありがとうございます, I got it now :) I'll work on it soon to provide a fix.

@tokyoincode I'll fix the `Object.assign` at the same time.

**Comment by tokyoincode** [comment]
Thank you @kemar! 😄
