### ISSUE TITLE
How to translate text in placeholder

### ISSUE THREAD

**Issue by barakat-turki** [Polyconseil/vue-gettext#57]

**Comment by kemar** [comment]
Since `placeholder` is an attribute, you can't.

It's a known issue: https://github.com/Polyconseil/vue-gettext#known-issues Please read the documentation before opening an issue. It will save your time and mine.

**Comment by barakat-turki** [comment]
Ok, sorry about that,
but there a way to extract a text by js method like `vm.$gettext`.
is it can translate a text to pot file?
