### ISSUE TITLE
Lazy $translations update or change (request)

### ISSUE THREAD

**Issue by dazbo** [Polyconseil/vue-gettext#58]
The plugin expose $translation by attaching a property to the `Vue` object (at the end of the `index.js` file).
What is the purpose of this exposition? how to use it?

Related to this issue #12 this can be a way to update/change internal dictionary used to retrieve translation.

I try (using a fast and dirty modification) to expose this same property to the prototype
``` js
// Exposes global properties.
Vue.$translations = options.translations;
Vue.prototype.$translations = options.translations;
```
or
```js
languageVm = new Vue({
		created: function () {
			// Non-reactive data.
			this.available = options.availableLanguages;
		},
		data: {
			current: options.defaultLanguage,
			availableTranslations: options.translations // expose translation with an available property
		},
		mixins: [options.languageVmMixin],
	});
```

and it looks that updates or changes can be done inside a component, and they are reflected inside the Vue application.
Now it's to the developer to manage merge/removal or add to this dictionary.

What are the drawback of this change?

**Comment by kemar** [comment]
`$translations` is exposed globally so it can be [accessed easily](https://github.com/Polyconseil/vue-gettext/blob/db9f9448b889ff993a3a7aec03928d38096e0d29/src/translate.js#L29) through the code base.

What would be the use case to update or change `$translations` inside of a component?

**Comment by dazbo** [comment]
The initial purpose was to be able to load 'chunk' of translations, so each components (or at least very specific one) to load and add related translation entries only when load/mounted rather than loading the whole application entries.
Also, we tried to be able to add more languages based on user selection and choice into the application.

I will try to provide a code sample with the proposed change, maybe it will help to understand the purpose of the request/question.

Anyway, our project is on standby for now, the request is not really urgent, but thanks for your plugin and time!

**Comment by kemar** [comment]
Ok, I'm closing this for now. Feel free to reopen it if you encounter this issue again.
