### ISSUE TITLE
"No translations found" warning for default language

### ISSUE THREAD

**Issue by amir-hadi** [Polyconseil/vue-gettext#60]
We see "No translations found for en_US" warnings, but en_US is the language of the code. So why should we translate it? Did I configure something wrong or is this a bug?

Using vue-gettext in version 2.0.23.

**Comment by kemar** [comment]
You don't have to translate your default language.

But you still have to follow a [basic `gettext` workflow](https://github.com/Polyconseil/vue-gettext#workflow) until your translated `.po` files become usable in your Vue.js app. This [warning](https://github.com/Polyconseil/vue-gettext/blob/06e3dfe66666e050a3566d24127048bfb6f6f320/src/translate.js#L33) means that you didn't reach the [compilation step](https://github.com/Polyconseil/vue-gettext#4-compiling-translations).

If you know what you're doing, you can toggle the [`silent`](https://github.com/Polyconseil/vue-gettext#configuration) option to enable or disable logs/warnings for missing translations and untranslated keys.

**Comment by kemar** [comment]
Update: fixed in #62.
