### ISSUE TITLE
translation missing message when default language is set

### ISSUE THREAD

**Issue by eregnier** [Polyconseil/vue-gettext#61]
I have generated translation files for all my languages except the one used il my app, because I don't need to generate a po file where msgid = msgstr everywhere.

I think when default language is set (or maybe another parameter should do the trick), no warning message should be output.

Maybe am I missing something to do this, but at the moment, the messages are filling the console when I toggle my app in the base language user in my app (fr, this is legacy).

**Comment by kemar** [comment]
Yes, this is the current state of the plugin: a `.po` file is required for any available language, even the default one.

Please, have a look at this response: https://github.com/Polyconseil/vue-gettext/issues/60#issuecomment-358696996 in issue #60.

I can understand that this can be a bit of a nuisance. I'm too busy now to work on it, but feel free to submit a PR if it becomes unbearable.

**Comment by kemar** [comment]
Closed by #62
