### ISSUE TITLE
Issue with Arabic

### ISSUE THREAD

**Issue by arthursouviron** [Polyconseil/vue-gettext#69]
Hi,

Basic use of the ```v-translate``` directive does not work for Arabic.
I was able to identify what I think is causing the issue.

Assuming we are using this template :
```<div class="title" v-translate>History</div>```

And the translations.json file is as follow:
```
{
	"ar": {
		"History": "History Arabic"
	}
}
```

When it goes into the ```getTranslation```, I get the following parameters
![screen shot 2018-04-26 at 16 08 31](https://user-images.githubusercontent.com/5681289/39293756-506fd4a8-496c-11e8-8685-cdf89d033d96.png)
:

The first line of that ```getTranslation``` function will set the `n` attribute to 1.
Later, that ```n``` attribute will get passed to the ```getTranslationIndex``` function and in the switch statement for ```ar``` you have the following :
![screen shot 2018-04-26 at 16 11 34](https://user-images.githubusercontent.com/5681289/39293876-b2140120-496c-11e8-8ddc-c88744701e3b.png)

This will return 1 instead of 0 and will result in translation not found.

The only work around I found for now was to set a ```translate-n="0"``` everywhere I use v-translate.

**Comment by kemar** [comment]
Thank you for the report. I'll try to fix it asap.

**Comment by arthursouviron** [comment]
Thanks a lot for the quick fix!
