### ISSUE TITLE
Possibility to specify which translation file to use

### ISSUE THREAD

**Issue by MartinVandersteen** [Polyconseil/vue-gettext#70]
Hello!

My use case is that we have a central VueJS app that renders our different client platform's based on their setting, design informations, etc. All those informations come from the database.

Do you think it would be possible for us to have a group of translation files for each of our clients, that would be retrieved at the start of the application via HTTP get or something?

Thanks in advance for your help!

**Comment by kemar** [comment]
Hello,

This cannot be done with the plugin in its current state.

You can have a look at https://github.com/Polyconseil/vue-gettext/issues/12 if you want ideas to implement this feature by yourself.
