### ISSUE TITLE
Some strings are not translated on a language change

### ISSUE THREAD

**Issue by brunobg** [Polyconseil/vue-gettext#73]
I noticed that strings in other components are not always changed when the $vm.language is, particularly siblings of the parent component. It's a bit involved to provide a test case, but I could debug and help to fix this. Is there at least a workaround to force "redraw every component with the new strings"? a this.forceUpdate() applies only to the current component, which is already updated properly.

**Comment by kemar** [comment]
Not to my knowledge, [forceUpdate](https://vuejs.org/v2/api/#vm-forceUpdate) is a part of the Vue's API, not a part of vue-gettext.

I cannot help you without a link to a [minimal reproduction](https://github.com/vuejs/vue-issue-helper/blob/428607cb6601bdee4c0eb46f3592cffd36fbc544/src/i18n/locales/en/repro-modal.md) of your problem.

Meanwhile, make sure your [vue-gettext's configuration](https://github.com/Polyconseil/vue-gettext#configuration) is good, in particular `muteLanguages` and `silent` to ensure that missing translations warnings are enabled.

I'm closing this until you can provide a minimal reproduction case. At that time feel free to re-open it.
