### ISSUE TITLE
Document how to run gettext from within store

### ISSUE THREAD

**Issue by sandroden** [Polyconseil/vue-gettext#83]
There is already an open issue, #76 on a request to run gettext from a custom module. It's been there since october. I also created a codesandbox to show that the solution suggested is failing for me.

While I really hope there is a solution that I wasn't able to find, I'd like that you document either the solution or the fact that you cannot use gettext from within store and custom modules.

**Comment by kemar** [comment]
gettext has it's own documentation https://www.gnu.org/software/gettext/manual/gettext.html I won't read it for you.

**Comment by sandroden** [comment]
I'm afraid there has been a misunderstanding. 

I'm not asking how gettext works (I have been using it from python for over 15 years) but how can I use vue-gettext's `$gettext` in a vuex store .  That's strictly specific of vue and specifically vue-gettext plugin implementation (and possibly of javascript?).

You are very accurate in the documentation explaining how to use it in `.vue` component, simply I wasn't able to get to that `$gettext` object in the store. 

I'm not the first to ask this question and really I don't understand your tone. As I'm pretty new to vue and js I may have missed some info that makes it obvious how to use it, that's why I created the [sandbox](https://codesandbox.io/s/lp21z7jpm9) . What's the point of having such accurate documentation if you're not interested in what blocks your users? Let at least me know if you don't answer because you consider a too easy problem to bother answering or too difficult one for which you have no interest in.

**Comment by kemar** [comment]
I've closed this issue as a duplicate of #76

@sandroden I'm maintaining this project on my free time and I'm doing by best to help users. Opening a new issue because the previous one hasn't been closed is not the way it works.
