### ISSUE TITLE
Makefile fails to maintain template.pot on multi-user system 

### ISSUE THREAD

**Issue by Fadiabb** [Polyconseil/vue-gettext#86]
* since Makefile uses **template.pot** in its process, the parallel use of several 
   users causes interference on this file(multi-user system).
 * the actual status of this file could not be maintained to all users if e.g. 
   `makemessages` Makefile executed from differnet users.

**reproduce the problem:**
 * user A calls `makemessages`, this changes the **template.pot** file 
 * when user B calls `makemessages` too, this leads to have interference on this file (the actual status of this file is lost to some users)

**Comment by Fadiabb** [comment]
### solution:
add the name of the user to `template.pot` filename so each user has his own file,this keeps the behavior of this file  as it is.  
we solved this problem with this commit: [https://hg.intevation.de/gemma/rev/dd9d90cae683](https://hg.intevation.de/gemma/rev/dd9d90cae683)

**Comment by bernhardreiter** [comment]
One problem is: Because user A created the file, user B cannot write it.
