### ISSUE TITLE
Incorrect $gettextInterpolate signature value

### ISSUE THREAD

**Issue by tcitworld** [Polyconseil/vue-gettext#95]
```ts
$gettextInterpolate: (msgid: string, context: object) => string;
```
should be
```ts
$gettextInterpolate: (msgid: string, context: object, disableHtmlEscaping: boolean) => string;
```

**Comment by junish** [comment]
> $gettextInterpolate: (msgid: string, context: object, disableHtmlEscaping: boolean) => string;

According to [a test case](https://github.com/Polyconseil/vue-gettext/blob/1b44cc38f1b9e47d4713db7372e0c79a271c84a5/test/specs/interpolate.spec.js#L32-L37), `disableHtmlEscaping` contains `undefined`. So it should be

```js
$gettextInterpolate: (msgid: string, context: object, disableHtmlEscaping?: boolean) => string;
```

Is it right?

**Comment by tcitworld** [comment]
@kemar :arrow_up:

**Comment by tcitworld** [comment]
Thanks !
